from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "59pT3uH9B5RlO2O8VUTD6p29"

# Found in the 'Manage Deployment' page
CLOUD_ID = "quickstart-es-http:10.107.177.101"

# Create the client instance
es = Elasticsearch(
    "https://localhost:9200",
    basic_auth= ("elastic","59pT3uH9B5RlO2O8VUTD6p29"),
    ca_certs="quickstart-es-http",
    verify_certs=False
    
)
# Successful response!
es.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}